# Generated by Django 5.0.4 on 2024-04-28 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='website',
        ),
    ]
